LANGUAGE_DATA = ["python", "go", "java", "javascript", "c/c++", "c#", "front end", "QA"]


REVIEWER_DATA = [
    ("Alex", "Langhart", ["java"]),
    ("Ben", "Ross", ["go", "python"]),
    ("Bill", "Lamkin", ["java"]),
    ("Bob", "Bawn", ["go", "java", "python", "c/c++", "c#"]),
    ("Charley", "Pinkerton", ["go", "java"]),
    ("Dan", "Maples", ["go", "java", "c/c++", "QA"]),
    ("David", "Harris", ["QA"]),
    ("Darrell", "Piner", ["java", "python", "c/c++"]),
    ("Dillon", "Corkran", ["javascript", "front end"]),
    ("Eric", "Wahlgren-Sauro", ["front end"]),
    ("Errett", "Allen", ["QA"]),
    ("Don", "Byington", ["go", "javascript"]),
    ("Ian", "Cahoon", ["go"]),
    ("Ian", "Stepheson", ["go", "java", "javascript"]),
    ("Jared", "Cantwell", ["go"]),
    ("Jefferson", "Pecht", ["front end"]),
    ("Jen", "Roos", ["QA"]),
    ("John", "Alfano", ["front end"]),
    ("Jon", "Casey", ["go", "java", "javascript", "python"]),
    ("Jordan", "Montgomery", ["go"]),
    ("Josh", "Small", ["front end"]),
    ("Josh", "Walker", ["go", "c/c++", "c#"]),
    ("Kevin", "Pickard", ["go", "python", "QA"]),
    ("Kevin", "Roberts", ["java", "javascript", "c#", "front end"]),
    ("Les", "Shupe", ["QA"]),
    ("Linda", "Silverthorn", ["front end"]),
    ("Marc", "Waldthausen", ["go", "java", "javascript"]),
    ("Matt", "Conover", ["javascript", "front end"]),
    ("Michael", "Vienneau", ["python"]),
    ("Mike", "DiLorenzo", ["javascript", "front end"]),
    ("Peter", "Gengler", ["go", "javascript", "python"]),
    ("Phil", "Deuchler", ["go", "java", "javascript", "python"]),
    ("Priyanka", "Nawalramka", ["go", "java"]),
    ("Rachel", "Adducci", ["go", "javascript"]),
    ("Raji", "Natarajan", ["QA"]),
    ("Rob", "Allen", ["java"]),
    ("Ryan", "Casperson", ["python"]),
    ("Robert", "Mulley", ["go"]),
    ("Sam", "Harvanek", ["QA"]),
    ("Saroch", "Panichsakul", ["python", "QA"]),
    ("Terry", "Smith", ["go", "java", "javascript", "python"]),
    ("Tom", "Foster", ["QA"]),
    ("Thomas", "Pritchard", ["go", "java"]),
    ("Trent", "Lamphere", ["go", "c/c++"]),
    ("Tristan", "Miller", ["go", "java", "c#"]),
    ("Rob", "Allen", ["go"]),
    ("Wayne", "Steidley", ["javascript", "front end"]),
    ("Zach", "Steiner", ["front end"]),
]
