version: '2.3'
services:
  postgres10:
    image: postgres:10
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - postgres10
    environment:
      - APP_SQL_URL=postgresql://postgres10/review_app
