version: '2.3'
services:
  postgres10:
    image: postgres:10
    env_file: database.conf
    user: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data 

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - postgres10
    environment:
      - APP_SQL_URL=postgresql+psycopg2://postgres:jumpcloud@postgres10/review_app
volumes:
  postgres-data: {}
  